version: "3"
services:
  vue3_admin_mysql:
    image: registry.cn-shanghai.aliyuncs.com/wangjian3306/mysql:8.0
    container_name: vue3_admin_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vue3_admin
      MYSQL_USER: vue3_admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init-sql/:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password

  vue3_admin_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue3_admin_backend
    restart: always
    environment:
      TZ: Asia/Shanghai
      VUE3_ADMIN_MYSQL_USER: vue3_admin
      VUE3_ADMIN_MYSQL_DATABASE: vue3_admin
      VUE3_ADMIN_MYSQL_PASSWORD: password
      VUE3_ADMIN_MYSQL_HOST: vue3_admin_mysql
      VUE3_ADMIN_REDIS_HOST: vue3_admin_redis # 这里要对应下面 redis 的 container_name
    ports:
      - "10086:10086"
    depends_on:
      - vue3_admin_mysql
      - redis

  redis:
    image: redis:alpine
    container_name: vue3_admin_redis # 👈 确保这个名字被后端环境变量引用
    ports:
      - "6379:6379"
